export const MutationTypes = Object.freeze({

  /**
   * Navigation driver
   */
  UPDATE_V_NAVIGATION_DRIVER: 'UPDATE_V_NAVIGATION_DRIVER',
  TOGGLE_V_NAVIGATION_DRIVER: 'TOGGLE_V_NAVIGATION_DRIVER',
  UPDATE_USER_V_NAVIGATION_DRIVER: 'UPDATE_USER_V_NAVIGATION_DRIVER',

  /**
   * App bar
   */
  UPDATE_V_APP_BAR: 'UPDATE_V_APP_BAR',
  TOGGLE_V_APP_BAR: 'TOGGLE_V_APP_BAR',

  /**
   * Loading
   */
  UPDATE_GLOBAL_LOADING: 'UPDATE_GLOBAL_LOADING',
  TOGGLE_GLOBAL_LOADING: 'TOGGLE_GLOBAL_LOADING',

  /**
   * Overlay
   */
  UPDATE_V_OVERLAY: 'UPDATE_V_OVERLAY',

  /**
   * Snackbar
   */
  UPDATE_SYSTEM_SNACKBAR: 'UPDATE_SYSTEM_SNACKBAR',
  TOGGLE_SYSTEM_SNACKBAR: 'TOGGLE_SYSTEM_SNACKBAR',
  SET_TYPE_SYSTEM_SNACKBAR: 'SET_TYPE_SYSTEM_SNACKBAR',

  /**
   * Snackbar messages
   */
  SET_SYSTEM_SNACKBAR_MESSAGES: 'UPDATE_SYSTEM_SNACKBAR_MESSAGES',
  APPEND_SYSTEM_SNACKBAR_MESSAGES: 'APPEND_SYSTEM_SNACKBAR_MESSAGES',
  CLEAR_SYSTEM_SNACKBAR_MESSAGES: 'CLEAR_SYSTEM_SNACKBAR_MESSAGES',
});
